run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gocyclo
    - gosec
    - prealloc
    - bodyclose
    - gofmt
    - goimports
