// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock_test.go -package=httpapi_test
//

// Package httpapi_test is a generated GoMock package.
package httpapi_test

import (
	context "context"
	reflect "reflect"
	domain "subscription_service/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MocksubscriptionService is a mock of subscriptionService interface.
type MocksubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MocksubscriptionServiceMockRecorder
	isgomock struct{}
}

// MocksubscriptionServiceMockRecorder is the mock recorder for MocksubscriptionService.
type MocksubscriptionServiceMockRecorder struct {
	mock *MocksubscriptionService
}

// NewMocksubscriptionService creates a new mock instance.
func NewMocksubscriptionService(ctrl *gomock.Controller) *MocksubscriptionService {
	mock := &MocksubscriptionService{ctrl: ctrl}
	mock.recorder = &MocksubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubscriptionService) EXPECT() *MocksubscriptionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocksubscriptionService) Create(ctx context.Context, sub domain.Subscription) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sub)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksubscriptionServiceMockRecorder) Create(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksubscriptionService)(nil).Create), ctx, sub)
}

// Delete mocks base method.
func (m *MocksubscriptionService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocksubscriptionServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocksubscriptionService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MocksubscriptionService) GetByID(ctx context.Context, id string) (domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksubscriptionServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksubscriptionService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MocksubscriptionService) List(ctx context.Context, userID, serviceName string) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, serviceName)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocksubscriptionServiceMockRecorder) List(ctx, userID, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocksubscriptionService)(nil).List), ctx, userID, serviceName)
}

// Total mocks base method.
func (m *MocksubscriptionService) Total(ctx context.Context, filter domain.Subscription) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Total", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Total indicates an expected call of Total.
func (mr *MocksubscriptionServiceMockRecorder) Total(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Total", reflect.TypeOf((*MocksubscriptionService)(nil).Total), ctx, filter)
}

// Update mocks base method.
func (m *MocksubscriptionService) Update(ctx context.Context, sub domain.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MocksubscriptionServiceMockRecorder) Update(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocksubscriptionService)(nil).Update), ctx, sub)
}
